---
title: "Installatierichtlijnen BMK software"
author: "Thierry Onkelinx"
output: 
  INBOmd::inbo_rapport:
    subtitle: "Versie voor eindgebruikers"
    cover: "useR-large.png"
    reportnr: "7 mei 2015"
    year: 2015
    email: thierry.onkelinx@inbo.be
    cover_offset: 150mm
    cover_text: "Het R logo"
    keep_tex: false
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Installatierichtlijnen BMK software, versie voor eindgebruikers}
  \usepackage[utf8]{inputenc}
---

# Inleiding

In deze handleiding vind je de nodige stappen die de eindgebruiker nog moet zetten om configuraties volledig gebruiksklaar te maken. De eigenlijke installatie dient te gebeuren met administratorrechten en is daarom in een ander document beschreven.

Mocht iets niet duidelijk zijn, neem dan contact op met Thierry Onkelinx. Krijg je een onverwacht dialoogvenster: maak dan een schermafdruk en stuur die naar Thierry Onkelinx.

## Basisconfiguratie

De basisconfiguratie omvat `R` en `RStudio`. Deze configuratie wordt bij alle R gebruikers geïnstalleerd.

## Geavanceerde configuratie

De geavanceerde configuratie is bevat een set extra tools bovenop de basisconfiguratie. De meeste gebruikers hebben deze tools niet nodig en hoeven ze daarom niet te configureren.






















# In te stellen door de gebruiker bij de basisconfiguratie

## Eenmalig bij een nieuwe installatie van R

1. Zorg dat de computer verbonden is met het internet
1. Start `R x64` via het menu start
1. Er zullen nu packages gedownload en geïnstalleerd worden. Dit duurt een poosje.
1. Wacht tot de installatie volledig afgelopen is
1. Tik vervolgens het commando `q()` gevolgd door enter. `R` zal nu afgesloten worden.

## Minstens een keer na een upgrade van R

1. Zorg dat de computer verbonden is met het internet
1. Start `R x64` via het menu start
1. Tik het commando `update.packages(ask = FALSE, checkBuilt = TRUE)` gevolgd door enter.
1. Er zullen nu packages waarvan een nieuwe versie beschikbaar is gedownload en geïnstalleerd worden. Dit duurt een hele poos, afhankelijk van het aantal te upgraden packages.
1. Wacht tot de installatie volledig afgelopen is
1. Tik vervolgens het commando `q()` gevolgd door enter. `R` zal nu afgesloten worden.

Je kan dit later herhalen als de deee geïnstalleerde packages wenst te upgraden.

## Eerste configuratie van RStudio

1. Voer eerst de stappen in `R` uit
1. Start `Rstudio` via het Start-menu
1. Wacht tot dat `RStudio` volledig opgestart is (witte scherm is vervangen)
1. Kies in het menu `Tools -> Global Options`
1. Pas de _initial working directory_ aan naar de locatie waar je `R` versie staat (`C:/R/R-3.x.y`)^[x en y verwijzen naar het versienummer. Dus bij R-3.1.0 is x = 1 en y = 0. De working directory is in dat geval `C:/R/R-3.1.0`]
1. _Restore .RData into workspace at startup:_ `uitvinken`
1. _Save workspace to.RData on exit:_ `Never`
1. _Default text encoding:_ klik op _Change_, kies `UTF-8` en klik _OK_.
1. Ga naar het tabblad _Packages_. _CRAN mirror:_ wijzigen naar `Global (CDN) - RStudio`
1. Ga naar het tabblad _Code editing_ en vink `Soft-wrap R source files` aan
1. Ga naar het tabblad _Appearance_ en stel in naar eigen smaak
1. Klik op _OK_ en herstart `RStudio`























## Configuratie van RStudio na een upgrade van R

1. Voer eerst de stappen uit bij de upgrade van `R`
1. Start `RStudio`
1. Kies in het menu `Tools -> Global Options`
1. Indien niet de laatste versie vermeld staat bij R version: klik op _Change_ om het aan te passen.
1. Klik op _OK_ als je een waarschuwing krijgt dat je `RStudio` moet herstarten.
1. Wijzig de initial working directory in `C:/R/R-3.x.y`^[x en y verwijzen naar het versienummer. Dus bij R-3.1.0 is x = 1 en y = 0. De working directory is in dat geval `C:/R/R-3.1.0`]
1. Klik op _OK_
1. Herstart `RStudio`

## Installatie en update van INBOtheme

1. Start RStudio
1. Voer volgend R commando uit:  
`devtools::install_git("https://git.milieuinfo.be/scm/~thierry_onkelinx/inbotheme.git", build_vignettes = TRUE)`






















# In te stellen door de gebruiker bij de geavanceerde configuratie

Bij de geavanceerde configuratie moet je eerst alle instellingen van de basisconfiguratie uitvoeren.

## MikTex

1. Ga in het _Start_ menu naar de _MikTex_ map.
1. Start _Update_ in de submap _Maintainance_.
1. Selecteer _remote package repository_ en _nearest package repository_ en klik tenslotte op _Volgende_.
1. Klik op _Volgende_.
1. Klik op _Volgende_.

## Installatie en update van INBOmd

1. Start RStudio
1. Voer volgend R commando uit:  
`devtools::install_git("https://git.milieuinfo.be/scm/~thierry_onkelinx/inbomd.git", build_vignettes = TRUE)`
1. Ga in het _Start_ menu naar _Alle programmas_ --> _MikTex 2.9_ --> _Maintenance_ --> _Settings_
1. Ga naar het tabblad _Roots_. Ga na of `C:\R\library\INBOmd\local_tex` in de lijst voorkomt. Zo niet, klik je op de knop _Add_, selecteer je `C:\R\library\INBOmd\local_tex` en klik je op _OK_ en vervolgens op _Toepassen_.
1. Indien  `C:\R\library\INBOmd\local_tex` niet bovenaan de lijst van _Roots_ staat, selecteer je  
`C:\R\library\INBOmd\local_tex` en klik op _Up_ tot dat het bovenaan de lijst staat.
1. Ga naar het tabblad _General_. 
1. Klik op _Refresh FNDB_.
1. Klik op _Update formats_.
1. Klik op _OK_























# Aanbevolen R packages

## Gegevens inlezen en exporteren

| Package | Korte omschrijving                                                  |
|---------|---------------------------------------------------------------------|
| RODBC | gegevens importeren en exporteren via ODBC (Access, SQL server, ...)|
| XML | XML data inlezen |
| foreign | gegevens uit andere pakketten inlezen|
| rgdal | import en export van spatiale data |
| RCurl | gegevens inlezen vanaf website |

## Gegevens bewerken

| Package | Korte omschrijving                                                  |
|---------|---------------------------------------------------------------------|
| plyr | bewerking toepassen per subsets van data |
| reshape | gegevens omzetten van breed naar lang formaat en omgekeerd |
| reshape2 | gegevens omzetten van breed naar lang formaat en omgekeerd^[minder flexibel dan reshape, doch efficiënter] |
| lubridate | bewerkingen met tijd en/of datum |

## Grafieken maken

| Package | Korte omschrijving                                                  |
|---------|---------------------------------------------------------------------|
| ggplot2 | grafieken maken |
| scales | aangepaste schalen voor ggplot2 grafieken |
| INBOtheme | INBO huisstijl voor ggplot2 grafieken |
| lattice | grafieken maken^[nog flexibeler dan ggplot2, doch moeilijkere code] |
| coefplot2 | grafisch weergeven van parameterschattingen van regressiemodellen |

## Gegevens analyseren

| Package | Korte omschrijving                                                  |
|---------|---------------------------------------------------------------------|
| lme4 | mixed models met gekruiste random effects. gaussiaans, poisson of binomiaal |
| nlme | mixed models met correlatie- of variantiestructuur. gaussiaans |
| multcomp | meervoudige vergelijkingen van resultaten (o.a. Tukey) |
| zoo | analyse van tijdsreeksen |
| cluster | clusteranalyses |
| quantreg | kwantielregressie |
| mgcv | gam smoothers |
| vegan | analyse van vegetatieopnames |
| INLA | Bayesiaanse mixed models met INLA |
| MCMCglmm | Bayesiaanse mixed models met MCMC |
| gamm4 | mixed model uitbreiding van gam |
| glmmADMB | uitbreiding voor mixed models (negative binomial, ...) |
| geepack | generalised estimating equations |

## Spatiale gegevens

| Package | Korte omschrijving                                                  |
|---------|---------------------------------------------------------------------|
| sp | basisklassen en bewerkingen voor spatiale data |
| rgdal | spatiale bewerkingen  + import en export|
| maptools | shapefiles inlezen + bewerkingen |
| gstat | variogram en kriging |

## Tools

| Package | Korte omschrijving                                                  |
|---------|---------------------------------------------------------------------|
| knitr | Tekst en R code combineren in een bronbestand |
| rmarkdown | Markdown teksten compileren in R |
| xtable | data.frame omzetten naar \LaTeX of HTML |
| pander | data.frame omzetten naar Markdown |
| devtools | installeer packages vanaf GitHub |
| roxygen2 | R code documenteren |
| microbenchmark | tijdsgebruik van code meten |
