---
title: "Installatierichtlijnen BMK software"
author: "Thierry Onkelinx"
output: 
  INBOmd::inbo_rapport:
    subtitle: "Versie voor personen met adminrechten"
    cover: "useR-large.png"
    reportnr: "7 mei 2015"
    year: 2015
    email: thierry.onkelinx@inbo.be
    cover_offset: 150mm
    cover_text: "Het R logo"
    keep_tex: false
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Installatierichtlijnen BMK software, versie voor administrators}
  \usepackage[utf8]{inputenc}
---

# Inleiding

In deze handleiding vind je de nodige instructies om een aantal statistische tools te installeren. De installatie dient te gebeuren met (local) admin-rechten. De handleiding veronderstelt dat je als (local) admin ingelogd bent. Om de installatie volledig af te ronden moet de gebruiker een aantal stappen uitvoeren. Deze vind je in een ander document.

Alle installatiebestanden bevinden zich op `P:\Algemeen\Algemene info\BMK\R`. Je kan ze ook downloaden van de websites. De links worden bij de instructies van elk package vermeld.

In de onderstaande tekst moet je in `R-3.x.y` zowel `x` als `y` vervangen door een cijfer om zo het huidige versienummer te krijgen. Dus voor versie `R-3.0.0` is `x` = 0 en `y` = 0.

Installatievolgorde:

1. R
1. Git
1. RStudio
1. RTools
1. MikTex























# R

Installatiebestand beschikbaar via http://cran.r-project.org/bin/windows/base/

## Nieuwe installatie van R

1. Maak de map `C:\R\library` aan. Zorg dat alle gebruikers volledige toegangsrechten hebben.
1. Voer het bestand _R-3.x.y-win.exe_ uit.
1. Kies _Nederlands_ als taal voor de installatie en klik op _OK_.
1. klik op _Volgende_.
1. Aanvaard de licentievoorwaarden door op _Volgende_ te klikken.
1. Kies als doelmap `C:\R\R-3.x.y` en klik op _Volgende_. Je **MOET** de standaardwaarde dus aanpassen!
1. Selecteer de gewenste componenten en klik op _Volgende_. Je **MOET** deze standaardwaarden laten staan.
1. Opstartinstelling aanpassen: Kies `Nee` en klik op _Volgende_.
1. Geef de map voor het start menu en klik op _Volgende_. Je mag de standaardwaarde gebruiken.
1. Vink alle extra snelkoppelingen _uit_, alle register entries _aan_ en klik op _Volgende_.
1. R wordt nu geïnstalleerd. Klik op _Voltooien_ als de installatie afgelopen is.
1. Ga naar `Start` -> `Configuratiescherm` -> `Systeem en beveiliging`. Selecteer het tabblad `Geavanceerd` en klik op de knop `Omgevingsvariabelen`. Ga na of er een systeemvariabele `R_LIBS_USER` met waarde `C:/R/library` bestaat^[Het moeten forward slashes zijn.]. Indien niet, maak deze aan met de knop `Nieuw`. Sluit al deze schermen via de `OK` knop.
1. Rechtsklik op de snelkoppeling (in het Start menu) naar `R x64 3.x.y` en kies eigenschappen.
1. Wijzig _Beginnen in_ naar `C:\R\R-3.x.y`
1. Voeg achteraan het veld _Doel_ de volgende tekst toe: `--no-save --no-restore`
1. Herhaal de laatste drie stappen voor de snelkoppeling naar `R i386 3.x.y`
1. Kopieer het bestand `Rprofile.site` naar `C:\R\R-3.x.y\etc` Hierbij moet je het bestaande bestand overschrijven.
1. Zorg dat de gebruiker schrijfrechten heeft voor `C:\R\R-3.x.y\library`

**R mag niet met admininstratorrechten gestart worden.** Anders worden een aantal packages met administrator rechten geïnstalleerd waardoor de gebruiker ze niet meer kan updaten.

Start `R` als een gewone gebruiker om de configuratie te testen.

## Upgrade van een bestaande R installatie

**Deze instructies veronderstellen dat R en RStudio in het verleden reeds geïnstalleerd werden volgens de bovenstaande instructies. Indien dan niet het geval is, volg dan de instructies voor een nieuwe installatie.**

1. Voer het bestand _R-3.x.y-win.exe_ uit.
1. Kies Nederlands als taal voor de installatie en klik op _OK_.
1. klik op _Volgende_.
1. Aanvaard de licentievoorwaarden door op _Volgende_ te klikken.
1. Kies als doelmap `C:\R\R-3.x.y` en klik op _Volgende_. Je **MOET** de standaardwaarde dus aanpassen!
1. Selecteer de gewenste componenten en klik op _Volgende_. Je **MOET** deze standaardwaarden laten staan.
1. Opstartinstelling aanpassen: Kies `Nee` en klik op _Volgende_.
1. Geef de map voor het start menu en klik op _Volgende_. Je mag de standaardwaarde gebruiken.
1. Vink alle extra snelkoppelingen _uit_, alle register entries _aan_ en klik op _Volgende_.
1. R wordt nu geïnstalleerd. Klik op _Voltooien_ als de installatie afgelopen is.
1. Rechtsklik op de snelkoppeling (in het Start menu) naar `R x64 3.x.y` en kies eigenschappen.
1. Wijzig _Beginnen in_ naar `C:\R\R-3.x.y`
1. Voeg achteraan het veld _Doel_ de volgende tekst toe: `--no-save --no-restore`
1. Herhaal de laatste drie stappen voor de snelkoppeling naar `R i386 3.x.y`
1. Kopieer het bestand `Rprofile.site` naar `C:\R\R-3.x.y\etc` Hierbij moet je het bestaande bestand overschrijven.
1. Zorg dat de gebruiker schrijfrechten heeft voor `C:\R\R-3.x.y\library`
1. De nieuwe R versie is klaar voor gebruik. De gebruiker moet `RStudio` bijwerken.

**R mag niet met admininstratorrechten gestart worden.** Anders worden een aantal packages met administrator rechten geïnstalleerd waardoor de gebruiker ze niet meer kan updaten.

Start `R` als een gewone gebruiker om de configuratie te testen.

























# Git

De installatiebestanden zijn beschikbaar via http://git-scm.com/downloads

1. Voer het installatiebestand uit
1. Welkom bij de installatie: klik op _Next_
1. Aanvaard de licentievoorwaarden door _Next_ te klikken
1. Gebruik de standaard componenten door _Next_ te klikken
1. Kies `use Git from the Windows Command Prompt` en klik _Next_
1. Kies `Checkout Windows-style, commit Unix-style line endingd` en klik _Next_
1. Klik op _Finish_


















# RStudio

De installatiebestanden zijn beschikbaar via http://www.rstudio.com/products/rstudio/download/

## Nieuwe installatie en upgrade van RStudio

RStudio upgraden doe je door de nieuwe versie te installeren over de oude.

1. Zorg dat eerst `R` geïnstalleerd is.
1. Het `Rstudio` installatiebestand staat in dezelfde map op de P-schijf als het  `R` installatie bestand. Kopiëer het naar je harde schijf
1. Voer het installatiebestand uit
1. Welkom bij de installatie: klik op _volgende_
1. Geef aan dat je `RStudio` wilt installeren in `C:\R\Rstudio` en klik op _volgende_.
1. Klik op _installeren_
1. Klik op _voltooien_

**RStudio mag niet met admininstratorrechten gestart worden.** Anders worden een aantal R packages met administrator rechten geïnstalleerd waardoor de gebruiker ze niet meer kan updaten.

Test de configuratie door RStudio te starten als een **_gewone_** gebruiker.




















# Rtools

## Installatie en upgrade

De installatiebestanden zijn beschikbaar via http://cran.r-project.org/bin/windows/Rtools/

1. Kies `Nederlands` als taal voor de installatie en klik _volgende_.
1. Klik _volgende_.
1. Klik _volgende_.
1. Wijzig de installatiemap naar `C:\R\Rtools` en klik _volgende_.
1. Selecteer in de dropdown box `Package authoring installation` en klik _volgende_.
1. Vink _Edit the system PATH_ aan, vink _Save versions information to registry_ aan en klik op _volgende_.
1. Klik _volgende_.
1. Klik _installeren_.
1. Klik _Voltooien_.
























# MikTex

## Nieuwe installatie

De installatiebestanden zijn beschikbaar via http://miktex.org/download


1. Gebruik indien mogelijk de 64-bit installer.
1. Start de installer en klik op _Uitvoeren_.
1. Aanvaard de voorwaarden en klik op _Volgende_
1. Selecteer _Anyone who uses this computer_ en klik op _volgende_.
1. In het veld _Install MikTeX to_ vul je `c:\R\MikTeX` in en klik op _volgende_.
1. Wijzig _Install missing packages on-the-fly_ naar `Yes` en klik op _volgende_.
1. Klik op _Start_.
1. Klik op _volgende_.
1. Klik op _close_.
1. Ga in het _Start_ menu naar de _MikTex_ map.
1. Start _Update (admin)_ in de submap _Maintainance (admin)_.
1. Selecteer _remote package repository_ en _nearest package repository_ en klik tenslotte op _Volgende_.
1. Klik op _Volgende_.
1. Klik op _Volgende_.

## Upgrade

Nog te schrijven
