---
title: "Voorbeeld bibliografie"
author: "Thierry Onkelinx"
bibliography: "INBOmd.bib"
output: 
  INBOmd::inbo_rapport_2015:
    reportnr: "8 december 2014"
    year: 2014
    email: thierry.onkelinx@inbo.be
    keep_tex: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Voorbeeld bibliografie}
  %\VignetteEncoding{UTF-8}
---

# De tekst

## Boeken

Volgens @Agresti2002 is ...

Een stelling [@Agresti2002].

Een stelling volgens volgens alfabetisch vermeldde referenties [@Agresti2002; @BanerjeeEtal2003; @Bolker2008; @DiggleRibeiro2007; @Kish_1965; @ZuurEtal2009].

Een stelling volgens chronologisch vermeldde referenties [@Kish_1965; @Agresti2002; @BanerjeeEtal2003; @DiggleRibeiro2007; @Bolker2008; @ZuurEtal2009].

## Hoofdstuk in een boek

Volgens @BlauwdrukVogels is ...

Een stelling [@BlauwdrukVogels].

Een stelling volgens volgens alfabetisch vermeldde referenties [@BlauwdrukVogels; @Degraer2013a; @BlauwdrukVleermuizen].

Een stelling volgens chronologisch vermeldde referenties [@Degraer2013a; @BlauwdrukVogels; @BlauwdrukVleermuizen].

## Rapporten

## Wetenschappelijk artikel

Volgens @Amano2012 is ...

Een stelling [@Amano2012].

Een stelling volgens twee referenties [@Amano2012; @Yli-Viikari2007].

## Tijdschrift artikel

Volgens @VanderMijnsbrugge2005 is ...

Een stelling [@VanderMijnsbrugge2005].

## Computer programma

Volgens @R-3.0.1 is ...

Een stelling [@R-3.0.1].

Een stelling volgens volgens alfabetisch vermeldde referenties [@R-3.0.1; @R-reshape].

Een stelling volgens chronologisch vermeldde referenties [@R-reshape, @R-3.0.1].


## Thesis

Volgens @MaStatThesis is ...

Een stelling [@MaStatThesis].

## Conference proceedings

Volgens @Onkelinx2012 is ...

Een stelling [@Onkelinx2012].

Een stelling volgens volgens alfabetisch vermeldde referenties [@Onkelinx2012; @Onkelinx2014a].

Een stelling volgens chronologisch vermeldde referenties [@Onkelinx2012; @Onkelinx2014a].

# Bibliografie
