on:
  push:
    branches-ignore:
      - ghpages

name: "check package with checklist"

jobs:
  check-package:
    runs-on: ubuntu-24.04
    name: check-package
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      RSPM: "https://packagemanager.posit.co/cran/__linux__/noble/latest"
    permissions:
      contents: read
    steps:
      - name: "Check package with checklist"
        uses: inbo/actions/check_pkg@a29089fc9a2ea38b9d9bd62c0d1db3b448b224c8 # composite
  deploy-pages:
    name: deploy-gh-pages
    runs-on: ubuntu-24.04
    needs: check-package
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    permissions:
      contents: write
    steps:
      - name: "Tag and deploy gh-pages"
        uses: inbo/actions/check_deploy@a29089fc9a2ea38b9d9bd62c0d1db3b448b224c8 # composite
